title: St Fatika Nabila Halim # your name (or website title) here
logo: "/images/Pict01.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>
  PZSIB Data Scientist 2022
  <br>
  Aktuaria ITS
  <br><br>
  <a href="https://www.instagram.com/fatikanabilaa/">View My Instagram Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
